apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/docker-0: https://<region>.ocir.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: <your-object-storage-name/your-user-name>
  password: <token>
