apiVersion: v1
data:
  script.js: |-
    import http from 'k6/http';
    import { sleep } from 'k6';

    export default function () {
        http.get('https://cowsay-caller-observability-demo.apps.ocidemo.ochacafe-openshift.net/remote/say');
        sleep(1)
    }
kind: ConfigMap
metadata:
  name: config
  namespace: observability-demo
