apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: ochacafe
        image: icn.ocir.io/orasejapan/ochacafe-rhos:1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "30"
spec:
  type: LoadBalancer
  ports:
  - name: ochacafe
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: go
