apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: observability
spec:
  config:
    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: tempo-tracing-tempo-distributor:4317
        tls:
          insecure: true
      otlphttp:
        endpoint: http://tempo-tracing-tempo-distributor:4318
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch: {}
      k8sattributes: {}
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
      resourcedetection:
        detectors: [openshift]
    service:
      pipelines:
        traces:
          exporters:
            - debug
            - otlp
          receivers:
            - otlp
          processors:
            - memory_limiter
            - k8sattributes
            - resourcedetection
            - batch
  managementState: managed
  targetAllocator:
    filterStrategy: relabel-config
    allocationStrategy: consistent-hashing
    prometheusCR:
      scrapeInterval: 30s
  configVersions: 3
